name: JOB - Generate EPG - Every 1 day

on:
  workflow_dispatch:
  
jobs:
  run_grabber:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        include:
          - python-version: "3.9"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup py-epg-grabber
        run: pip install git+https://github.com/akmalharith/epg-grabber.git@v0.4.0
      
      - name: Run py-epg-grabber
        run: cd epg && py-epg-cli local -f input.json -o tv.xml -d 1 -w 10 && gzip -f tv.xml
      
      - name: Commit & push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: gh-pages
          force: true
          
